package org.zp.tent.entity.mybatis.domain;

import java.util.Date;

public class SchedulerJob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.jobId
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private Short jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.jobName
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.jobGroup
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.jobClass
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private String jobClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.cronExpression
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.jobStatus
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private String jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.addTime
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.lastUpdate
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_scheduler_job.remark
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.jobId
     *
     * @return the value of t_scheduler_job.jobId
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public Short getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.jobId
     *
     * @param jobId the value for t_scheduler_job.jobId
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setJobId(Short jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.jobName
     *
     * @return the value of t_scheduler_job.jobName
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.jobName
     *
     * @param jobName the value for t_scheduler_job.jobName
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.jobGroup
     *
     * @return the value of t_scheduler_job.jobGroup
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.jobGroup
     *
     * @param jobGroup the value for t_scheduler_job.jobGroup
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.jobClass
     *
     * @return the value of t_scheduler_job.jobClass
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public String getJobClass() {
        return jobClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.jobClass
     *
     * @param jobClass the value for t_scheduler_job.jobClass
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setJobClass(String jobClass) {
        this.jobClass = jobClass == null ? null : jobClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.cronExpression
     *
     * @return the value of t_scheduler_job.cronExpression
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.cronExpression
     *
     * @param cronExpression the value for t_scheduler_job.cronExpression
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.jobStatus
     *
     * @return the value of t_scheduler_job.jobStatus
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.jobStatus
     *
     * @param jobStatus the value for t_scheduler_job.jobStatus
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus == null ? null : jobStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.addTime
     *
     * @return the value of t_scheduler_job.addTime
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.addTime
     *
     * @param addTime the value for t_scheduler_job.addTime
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.lastUpdate
     *
     * @return the value of t_scheduler_job.lastUpdate
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.lastUpdate
     *
     * @param lastUpdate the value for t_scheduler_job.lastUpdate
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_scheduler_job.remark
     *
     * @return the value of t_scheduler_job.remark
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_scheduler_job.remark
     *
     * @param remark the value for t_scheduler_job.remark
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}