package org.zp.tent.entity.mybatis.dao;

import org.zp.tent.entity.mybatis.domain.SchedulerJob;

public interface SchedulerJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scheduler_job
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    int deleteByPrimaryKey(Short jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scheduler_job
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    int insert(SchedulerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scheduler_job
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    int insertSelective(SchedulerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scheduler_job
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    SchedulerJob selectByPrimaryKey(Short jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scheduler_job
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    int updateByPrimaryKeySelective(SchedulerJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_scheduler_job
     *
     * @mbggenerated Thu Jul 07 15:10:03 CST 2016
     */
    int updateByPrimaryKey(SchedulerJob record);
}