package org.zp.tent.entity.mybatis.dao;

import org.zp.tent.entity.mybatis.domain.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sun Jul 10 23:32:41 CST 2016
     */
    int deleteByPrimaryKey(String user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sun Jul 10 23:32:41 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sun Jul 10 23:32:41 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sun Jul 10 23:32:41 CST 2016
     */
    User selectByPrimaryKey(String user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sun Jul 10 23:32:41 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Sun Jul 10 23:32:41 CST 2016
     */
    int updateByPrimaryKey(User record);

    List<User> getAllUser();
}