package org.zp.tent.entity.domain;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_birthday
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    private Date user_birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_salary
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    private Double user_salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param user_id the value for t_user.user_id
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param user_name the value for t_user.user_name
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_birthday
     *
     * @return the value of t_user.user_birthday
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public Date getUser_birthday() {
        return user_birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_birthday
     *
     * @param user_birthday the value for t_user.user_birthday
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public void setUser_birthday(Date user_birthday) {
        this.user_birthday = user_birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_salary
     *
     * @return the value of t_user.user_salary
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public Double getUser_salary() {
        return user_salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_salary
     *
     * @param user_salary the value for t_user.user_salary
     *
     * @mbggenerated Tue Jul 05 14:34:04 CST 2016
     */
    public void setUser_salary(Double user_salary) {
        this.user_salary = user_salary;
    }
}